// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["psql 'postgresql://neondb_owner:npg_E8C4mjnFgYHk@ep-curly-hat-a18p0ak7-pooler.ap-southeast-1.aws.neon.tech/gmmi-db-prod?sslmode=require&channel_binding=require'"],
  },
});
